-- =============================================================================
-- SupersDeck — Phase 5 storage setup
-- =============================================================================
-- Creates the `wo-photos` bucket (private) for work-order before/after images
-- and the matching RLS policies so signed-in users can upload, read, delete.
-- Run AFTER auth-setup.sql + role-policies.sql.
--
-- Why private? Photos can show tenant interiors / faces / property
-- conditions. Treat them like personal data. Reads use short-lived signed
-- URLs generated by the app on demand.
-- =============================================================================

-- ----------------------------- bucket --------------------------------------
insert into storage.buckets (id, name, public)
values ('wo-photos', 'wo-photos', false)
on conflict (id) do nothing;

-- ----------------------------- RLS on storage.objects ----------------------
-- Supabase enables RLS on storage.objects by default. We add scoped policies
-- so only authenticated users touching THIS bucket pass — other buckets you
-- might add later are unaffected.

drop policy if exists "wo-photos: authenticated upload" on storage.objects;
create policy "wo-photos: authenticated upload"
  on storage.objects for insert
  to authenticated
  with check (bucket_id = 'wo-photos');

drop policy if exists "wo-photos: authenticated read" on storage.objects;
create policy "wo-photos: authenticated read"
  on storage.objects for select
  to authenticated
  using (bucket_id = 'wo-photos');

drop policy if exists "wo-photos: authenticated update" on storage.objects;
create policy "wo-photos: authenticated update"
  on storage.objects for update
  to authenticated
  using (bucket_id = 'wo-photos')
  with check (bucket_id = 'wo-photos');

drop policy if exists "wo-photos: authenticated delete" on storage.objects;
create policy "wo-photos: authenticated delete"
  on storage.objects for delete
  to authenticated
  using (bucket_id = 'wo-photos');
