import { notFound } from "next/navigation";
import Link from "next/link";
import { db } from "@/lib/db";
import { createSupabaseServerClient } from "@/lib/supabase-server";
import PrintTrigger from "@/components/PrintTrigger";
import { toNormalized } from "@/lib/wo-adapter";
import { WorkOrderPrintSheet } from "@workorder/kit/print/WorkOrderPrintSheet";

// =============================================================================
//  /work-orders/[id]/print — printable Resident Service Order
// =============================================================================
//  Rendered by the shared @workorder/kit print sheet (one clean look across the
//  suite). Replaces the old monospace paper-form layout. Header entity comes
//  from buildings.legal_entity via the adapter; the resident's original-language
//  text prints under the English translation automatically.
// =============================================================================

async function fetchUnit(unitId: string | undefined) {
  if (!unitId) return null;
  const supabase = createSupabaseServerClient();
  if (!supabase) return null;
  const { data } = await supabase
    .from("units")
    .select("label")
    .eq("id", unitId)
    .maybeSingle();
  return (data as { label: string } | null) ?? null;
}

export default async function PrintWorkOrderPage({
  params,
}: {
  params: { id: string };
}) {
  const wo = await db.workOrder(params.id);
  if (!wo) notFound();

  const [building, unit] = await Promise.all([
    db.building(wo.building_id),
    fetchUnit(wo.unit_id),
  ]);

  return (
    <div className="bg-white">
      <div className="mx-auto flex max-w-[8.5in] items-center justify-between px-6 pt-4 print:hidden">
        <Link
          href={`/work-orders/${wo.id}`}
          className="rounded-md border border-ink-200 bg-white px-3 py-2 text-sm font-medium text-ink-600 hover:bg-ink-100"
        >
          ← Back to work order
        </Link>
        <PrintTrigger label="Print this work order" />
      </div>
      <WorkOrderPrintSheet
        wo={toNormalized(wo, { building, unit })}
        poweredBy="Generated by SupersDeck"
      />
    </div>
  );
}
