import type {
  Building,
  Unit,
  Vendor,
  WorkOrder,
  Certification,
  HeatLog,
} from "@/types";
import { generateUnitsForBuilding, FLOORS_PER_BUILDING } from "@/data/sample-data";

// =============================================================================
//  DEMO seed — a fully fictional "Maple Property Management" portfolio
// =============================================================================
//  Served ONLY when NEXT_PUBLIC_DEMO=1 (see src/lib/db.ts + the `supersdeck-demo`
//  launch config). Contains NO real address, tenant, or operational data, so it
//  is safe to screen-record for a portfolio. The demo is launched with empty
//  Supabase env, so the data layer can never reach the real database — this seed
//  is all the app can see. Unit shape is generated by the same helper the real
//  seed uses, so every page renders identically, just with invented data.
// =============================================================================

export const SAMPLE_BUILDINGS: Building[] = [
  {
    id: "demo-1",
    name: "Building 1",
    address: "100 Maple Avenue, Queens, NY 11000",
    borough: "Queens",
    year_built: 1975,
    num_units: 144,
    num_floors: 12,
    bin: "",
    bbl: "",
    hpd_id: "",
    community_district: "QN-06",
    has_section8: true,
    is_pact_rad: true,
    has_oil_heat: false,
    has_cooling_tower: false,
    has_sprinkler: true,
    has_known_lead: false,
    square_footage: 120000,
  },
  {
    id: "demo-2",
    name: "Building 2",
    address: "120 Maple Avenue, Queens, NY 11000",
    borough: "Queens",
    year_built: 1975,
    num_units: 144,
    num_floors: 12,
    bin: "",
    bbl: "",
    hpd_id: "",
    community_district: "QN-06",
    has_section8: true,
    is_pact_rad: true,
    has_oil_heat: false,
    has_cooling_tower: false,
    has_sprinkler: true,
    has_known_lead: false,
    square_footage: 120000,
  },
  {
    id: "demo-3",
    name: "Building 3",
    address: "140 Maple Avenue, Queens, NY 11000",
    borough: "Queens",
    year_built: 1975,
    num_units: 144,
    num_floors: 12,
    bin: "",
    bbl: "",
    hpd_id: "",
    community_district: "QN-06",
    has_section8: true,
    is_pact_rad: true,
    has_oil_heat: false,
    has_cooling_tower: false,
    has_sprinkler: true,
    has_known_lead: false,
    square_footage: 120000,
  },
];

export const SAMPLE_UNITS: Unit[] = [
  ...generateUnitsForBuilding("demo-1", FLOORS_PER_BUILDING),
  ...generateUnitsForBuilding("demo-2", FLOORS_PER_BUILDING),
  ...generateUnitsForBuilding("demo-3", FLOORS_PER_BUILDING),
];

// Day 1: empty (matches the real seed).
export const SAMPLE_MY_VENDORS: Vendor[] = [];

const today = new Date();
const daysAgo = (n: number) =>
  new Date(today.getTime() - n * 24 * 3600 * 1000).toISOString();

export const SAMPLE_WORK_ORDERS: WorkOrder[] = [
  {
    id: "demo-wo-1024",
    building_id: "demo-1",
    unit_id: "u-demo-1-7c",
    ticket_number: "WO-1024",
    title: "No heat in living room",
    description:
      "Tenant reports radiator cold in living room since last night; bedroom radiator works.",
    category: "no-heat",
    priority: "emergency",
    status: "triaged",
    reporter_name: "Alex Rivera",
    reporter_phone: "(555) 010-0101",
    reported_at: daysAgo(0),
    photos: [],
    hpd_risk: true,
  },
  {
    id: "demo-wo-1023",
    building_id: "demo-1",
    unit_id: "u-demo-1-3b",
    ticket_number: "WO-1023",
    title: "Kitchen sink slow drain",
    description: "Drains but slowly; tenant tried plunger.",
    category: "leak",
    priority: "normal",
    status: "assigned",
    reporter_name: "Jordan Lee",
    reported_at: daysAgo(1),
    assigned_to: "Sam (porter)",
    photos: [],
    hpd_risk: false,
  },
  {
    id: "demo-wo-1022",
    building_id: "demo-2",
    unit_id: "u-demo-2-11d",
    ticket_number: "WO-1022",
    title: "Front door lock sticking",
    description:
      "Tenant has to wiggle key; concerned about getting locked out.",
    category: "lock-key",
    priority: "high",
    status: "new",
    reporter_name: "Taylor Kim",
    reported_at: daysAgo(0),
    photos: [],
    hpd_risk: false,
  },
  {
    id: "demo-wo-1021",
    building_id: "demo-3",
    ticket_number: "WO-1021",
    title: "Lobby light out (east entrance)",
    description: "Lobby flicker then went out yesterday evening.",
    category: "common-area",
    priority: "normal",
    status: "completed",
    reporter_name: "Building staff",
    reported_at: daysAgo(2),
    resolved_at: daysAgo(0),
    assigned_to: "Sam (porter)",
    photos: [],
    hpd_risk: false,
  },
];

// Day 1: empty (matches the real seed).
export const SAMPLE_CERTIFICATIONS: Certification[] = [];
export const SAMPLE_HEAT_LOGS: HeatLog[] = [];
